### ISSUE TITLE
Issue while using Webpack

### ISSUE THREAD

**Issue by dnbard** [florian/x18n#15] opened 2016-06-23 09:58 UTC
> webpack -p

Hash: 4dcdc9637695882c3ed0
Version: webpack 1.13.0
Time: 10116ms
       Asset       Size  Chunks             Chunk Names
   vendor.js     253 kB       0  [emitted]  vendor
dashboard.js    37.5 kB       1  [emitted]  app
  index.html  340 bytes          [emitted]
   [0] multi vendor 148 bytes {0} [built]
    + 332 hidden modules

ERROR in ./~/x18n/lib/x18n.js
Module not found: Error: Cannot resolve module 'observable' in D:\project\node_modules\x18n\lib
 @ ./~/x18n/lib/x18n.js 194:4-196:6

Just added `x18n` and build stopped working.
I've tried to npm install `observable_js` in my project, but no success.

**Comment by stijnvanderlaan** [comment] 2016-07-14 12:00
running `npm install observable` did the trick for me

**Comment by florian** [comment] 2016-07-14 12:51
@stijnvanderlaan I don't understand how that solved the problem :/ The required lib is 'observable_js' and not 'observable'.
See [package.json](https://github.com/florian/x18n/blob/master/package.json#L19) and the [source code](https://github.com/florian/x18n/blob/master/lib/x18n.coffee#L131).

Are you sure that you're using the newest x18n version?

**Comment by jokester** [comment] 2016-08-04 05:07
Had this problem today with `x18n 2.0.1`.
This error is seemingly caused by previous AMD module dependency ([coffee](https://github.com/florian/x18n/blob/7d55d3cc3988c336d5e0f4b63eb83e72a302a23f/lib/x18n.coffee#L134) / [js](https://github.com/florian/x18n/blob/7d55d3cc3988c336d5e0f4b63eb83e72a302a23f/lib/x18n.js#L194)).

The fix for js is merged in [this commit](https://github.com/florian/x18n/commit/442e7d16d696a2e40650a7c85a157809d4d76809), but not included in v2.0.1.

Also I'm not sure about how is coffee/js used in this repo, maybe we should fix coffee as well.

**Comment by florian** [comment] 2016-09-24 10:34
Good catch @jokester!
Sorry for the late reaction, I was pretty busy the last weeks.

It should be fixed and pushed to NPM now :) If you still have problems, feel free to reopen the issue.

**Closed by florian** 2016-09-24 10:34 UTC
